name: Windows Workflow
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download file
      shell: bash
      run: |
        mkdir -p pragma
        curl -LJO https://github.com/Silverlan/pragma/releases/download/v1.0.5/pragma-v1.0.5-win64.zip
        unzip pragma-v1.0.5-win64.zip -d pragma

    - name: Run executable
      shell: bash
      run: |
        cd pragma
        #./pragma_server.exe
        #exit
        #echo ::set-output name=exit_code::%errorlevel%
        # Start pragma_server.exe in the background
        echo "A"
        ./pragma_server.exe &
        echo "B"
        # Store the process ID (PID) of the pragma_server.exe process
        pragma_server_pid=$!
        echo "C"
        # Wait for a short period to allow pragma_server.exe to start up
        sleep 5
        echo "D"
        # Send "exit" command to pragma_server.exe using a heredoc
        ./pragma_server.exe << EOF
        exit
        EOF
        echo "E"
        # Wait for pragma_server.exe to exit
        wait $pragma_server_pid
        echo "F"
        # Get the exit status of pragma_server.exe
        pragma_server_exit_code=$?
        echo "G"
        # Print the exit status
        echo "pragma_server.exe exit code: $pragma_server_exit_code"
        echo "H"

    - name: Check exit code
      shell: bash
      run: |
        echo Exit code: ${{ steps.run_executable.outputs.exit_code }}
