name: Windows Workflow
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download file
      run: |
        mkdir -p pragma
        curl -LJO https://github.com/Silverlan/pragma/releases/download/v1.0.5/pragma-v1.0.5-win64.zip
        tar -xf pragma-v1.0.5-win64.zip -C pragma

    - name: Run executable
      run: |
        cd pragma
        ./pragma_server.exe
        echo ::set-output name=exit_code::$LASTEXITCODE

    - name: Check exit code
      run: |
        echo Exit code: ${{ steps.run_executable.outputs.exit_code }}
        if [ ${{ steps.run_executable.outputs.exit_code }} -eq 0 ]; then
          echo "Success"
        else
          echo "Failure"
        fi
