name: Windows Workflow
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download file
      shell: bash
      run: |
        mkdir -p pragma
        curl -LJO https://github.com/Silverlan/pragma/releases/download/v1.0.5/pragma-v1.0.5-win64.zip
        unzip pragma-v1.0.5-win64.zip -d pragma

    - name: Run executable
      shell: bash
      run: |
        cd pragma
        ./pragma_server.exe +exit
        echo ::set-output name=exit_code::$?

    - name: Check exit code
      shell: bash
      run: |
        echo Exit code: ${{ steps.run_executable.outputs.exit_code }}
